# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---
annotations:
  licenses: "AGPL-3.0-only"
apiVersion: "v2"
dependencies:
  - name: "nubus-common"
    version: "^0.12.x"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
description: "A Helm Chart that deploys a standalone OpenLDAP server"
keywords:
  - "openldap"
  - "ldap"
name: "ldap-server"
sources:
  - "https://git.knut.univention.de/univention/customers/dataport/upx/container-ldap/-/tree/main/helm/ldap-server?ref_type=heads"
type: "application"
version: "0.11.0"
...
