# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---
annotations:
  licenses: "AGPL-3.0-only"
apiVersion: "v2"
description: "A Helm Chart that deploys a standalone OpenLDAP server"
keywords:
  - "openldap"
  - "ldap"
name: "ldap-server"
type: "application"
version: "0.11.0"

dependencies:
  - name: "nubus-common"
    version: "0.28.0-pre-dpapoutsis-nubus-common-templated-keymapping"
    repository: "oci://artifacts.software-univention.de/nubus-dev/charts"
