---

## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []

global:
  configMapUcrDefaults: "stack-data-ums-ucr"
  configMapUcr: "stack-data-swp-ucr"
  configMapUcrForced: null

# -- Application configuration of the OpenLDAP server
ldapServer:
  # -- TODO: Clarify usage of this parameter
  environment: "production"
  # -- Initial password to set for "cn=admin"
  ldapSecret: null

  # -- Whether to run an init container that waits for the IdP to be ready.
  waitForSamlMetadata: false

  # -- Path to the CA certificate.
  caCertFile: "/var/secrets/ca_cert"
  caCert: null
  # -- Path to the server certificate's public key in PEM format.
  certPemFile: "/var/secrets/cert_pem"
  certPem: null
  # -- Path to the server certificate's private key.
  privateKeyFile: "/var/secrets/private_key"
  privateKey: null
  # -- Path to the DH parameters
  dhParamFile: "/var/secrets/dh_param"
  dhParam: null


## Docker image
image:
  pullPolicy: "Always"
  pullSecrets: []
  registry: "registry.souvap-univention.de"
  repository: "souvap/tooling/images/univention-ldap/ldap-server"
  tag: "latest"
  # --  Define image sha256 as an alternative to `tag`
  sha256: ""

  # -- Image to use for the dependency waiter
  waitForDependency:
    registry: "gitregistry.knut.univention.de"
    repository: "univention/components/univention-portal/wait-for-dependency"
    imagePullPolicy: "Always"
    tag: "latest"
    # -- Define image sha256 as an alternative to `tag`
    sha256: ""


service:
  enabled: true
  type: ClusterIP
  ports:
    ldap:
      port: 389
      protocol: "TCP"
  sessionAffinity:
    enabled: false
    timeoutSeconds: 10800


## Deployment resources
resources:
  # requests:
  #   memory: "512Mi"
  #   cpu: "250m"
  # limits:
  #   memory: "4Gi"
  #   cpu: "4"


autoscaling:
  enabled: false


## Persistence storage configuration
persistence:
  sharedData:
    storageClass: ""
    size: "1Gi"
  sharedRun:
    storageClass: ""
    size: "1Gi"

...
