# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH
---

imagePullSecrets:
  - "kyverno-test"

# -- Set the amount of replicas of the primary statefulset.
replicaCountPrimary: 2

# -- Set the amount of replicas of the secondary statefulset.
replicaCountSecondary: 42

# -- Set the amount of replicas of the proxy deployment.
replicaCountProxy: 42

resourcesPrimary:
  limits:
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"

resourcesProxy:
  limits:
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"

...
