# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH
---

imagePullSecrets:
  - "kyverno-test"

# -- Set the amount of replicas of the primary statefulset.
replicaCountPrimary: 2

# -- Set the amount of replicas of the secondary statefulset.
replicaCountSecondary: 42

# -- Set the amount of replicas of the proxy deployment.
replicaCountProxy: 42

ldapServer:
  leaderElector:
    image:
      tag: "0.46.3@sha256:0c5c7b16c9a6aed2003bb18916783cad647a0efbf4d3d30cbf272b476e2e5c3b"

resourcesPrimary:
  limits:
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"

resourcesProxy:
  limits:
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"

...
