# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
{{ include "common.configMap" (dict "top" . "overrides" "ldap-notifier.configMap") }}

{{- define "ldap-notifier.configMap" }}
{{- with .top }}
data:
  ENVIRONMENT: "{{ .Values.ldapNotifier.environment }}"
  LDAP_SERVER_UID: "{{ .Values.ldapNotifier.ldapServerUid }}"
  LDAP_SERVER_GID: "{{ .Values.ldapNotifier.ldapServerGid }}"
{{- end }}
{{- end }}
