{{/*
SPDX-FileCopyrightText: 2024-2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ include "common.names.fullname" .  | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
data:
  ENVIRONMENT: {{ .Values.ldapNotifier.environment | quote}}
  LDAP_SERVER_UID: {{ .Values.ldapNotifier.ldapServerUid | quote}}
  LDAP_SERVER_GID: {{ .Values.ldapNotifier.ldapServerGid | quote}}
...
