# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

{{ include "common.service" (dict "top" . "overrides" "ldap-notifier.service") }}

{{- define "ldap-notifier.service" }}
{{- end }}
