---

stages:
- test-stage

image: python:3.7-alpine

variables:
  PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
  PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit

cache:
  paths:
  - .cache/pip
  - .cache/pre-commit
  - venv/

before_script:
- apk add gcc musl-dev libffi-dev make openssl-dev bash git shellcheck
- pip install virtualenv docker-compose
- if [ ! -f venv/bin/activate ]; then virtualenv venv; fi
- source venv/bin/activate
- pip install --upgrade pip

pre-commit-job:
  stage: test-stage
  when: manual
  script:
  - pip install pre-commit
  # Compose lint would fail without the referenced env files
  - cp .env.listener.example .env.listener
  - cp .env.univention-openldap.example .env.univention-openldap
  - SKIP=gitlab-ci-linter pre-commit run --all-files

...
