---

stages:
- test-stage

image: python:3.7

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

cache:
  paths:
  - .cache/pip
  - venv/

before_script:
- cat /etc/issue.net
- apt-get update
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate
- pip install --upgrade pip
- python --version
- pip --version
- which python
- which pip

pre-commit-job:
  stage: test-stage
  when: manual
  script:
  - apt-get --yes --verbose-versions install shellcheck
  - pip install pre-commit
  - pre-commit run --all-files

...
