---

include:
  - project: univention/customers/dataport/upx/common-ci
    file:
      - defaults/stages.yaml
      - defaults/souvap-workflow.yaml
      - templates/kaniko.yaml
      - jobs/lint-commit-messages.yaml
      - jobs/lint-pre-commit.yaml
      - jobs/package-and-publish-helm-charts.yaml


lint-pre-commit:
  before_script:
    - cp .env.ldap-server.example .env.ldap-server


deb-builder-image:
  stage: build
  extends: .kaniko
  needs: []
  variables:
    KANIKO_BUILD_CONTEXT: "images/ldap"
    DOCKERFILE_PATH: "images/ldap/Dockerfile_deb_builder"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/container-ldap-deb-builder"


build-ldap-image:
  stage: build
  extends: .kaniko
  needs:
    - deb-builder-image
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ldap-server"
    KANIKO_BUILD_CONTEXT: "images/ldap"
    KANIKO_ARGS: >-
      --build-arg DEB_BUILDER_TAG=$BUILD_VERSION


build-notifier-image:
  stage: build
  extends: .kaniko
  needs: []
  variables:
    KANIKO_BUILD_CONTEXT: "images/notifier"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/notifier-server"


# TODO: Remove once it's removed from common-ci
publish-helm-charts:
  rules:
    - when: never


# TODO: pending work below
# test-job:
#   stage: test-stage
#   tags:
#   - docker
#   image: ${UPX_IMAGE_REGISTRY}docker/compose:1.30-debian-buster-python-3.7.3
#   services:
#   - name: ${UNIV_DOCKERHUB_CACHE}library/docker:20.10.7-dind
#     alias: docker
#     command:
#     - --insecure-registry=artifacts.knut.univention.de
#     - --tls=false
#   script:
#   - cp .env.ldap-server.example .env.ldap-server
#   - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} pull
#   - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} up --detach --no-build
#   - cd integration-test
#   - docker-compose pull
#   - docker-compose up --no-build --exit-code-from test
#   - docker-compose rm
#   - ls -lah robot_results
#   - cd -
#   - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} down
#   - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} rm
#   artifacts:
#     when: always
#     expire_in: 4 weeks
#     reports:
#       junit: integration-test/robot_results/xunit.xml
#     paths:
#     - integration-test/robot_results
