---

stages:
- test-stage

image: docker-registry.knut.univention.de/pre-commit:container-ldap

variables:
  PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
  PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit

cache:
  paths:
  - .cache/pip
  - .cache/pre-commit
  - venv/

pre-commit-job:
  stage: test-stage
  when: manual
  script:
  # Compose lint would fail without the referenced env files
  - cp .env.listener.example .env.listener
  - cp .env.univention-openldap.example .env.univention-openldap
  - pre-commit run --all-files

...
