---

stages:
- test-stage

image: python:3.7-alpine

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

cache:
  paths:
  - .cache/pip
  - venv/

before_script:
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate
- pip install --upgrade pip

pre-commit-job:
  stage: test-stage
  when: manual
  script:
  - apk add gcc git musl-dev shellcheck
  - pip install pre-commit
  - pre-commit run --all-files

...
