---

# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH <info@univention.de>

include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.31.1"
    file:
      - "defaults/stages.yaml"
      - "defaults/nubus-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-external.yaml"
      - "jobs/package-and-publish-helm-charts-external.yaml"
      - "jobs/check-debian-updates.yaml"

  - project: "univention/dist/docker-services"
    ref: "master"
    file:
      - "dind.yml"

variables:
  # Used by pre-commit/gitlab-ci-linter
  GITLAB_PRIVATE_TOKEN: "${GITLAB_TOKEN}"
  GITLAB_PROJECT_ID: "${CI_PROJECT_ID}"
  GITLAB_SERVER: "https://git.knut.univention.de"

lint-pre-commit:
  before_script:
    - cp .env.ldap-server.example .env.ldap-server

.build-matrix: &build-matrix
  - IMAGE_NAME:
      - "ldap-server"
      - "ldap-notifier"
  - IMAGE_NAME: "testrunner"
    DOCKERFILE_PATH: "./docker/testrunner/Dockerfile"
  - IMAGE_NAME: "ldif-producer"
    DOCKERFILE_PATH: "./docker/ldif-producer/Dockerfile"

.publish-matrix: &publish-matrix
  - IMAGE_NAME:
      - "ldap-server"
      - "ldap-notifier"
      - "ldif-producer"

container-build:
  parallel:
    matrix: *build-matrix

container-generate-sbom:
  parallel:
    matrix: *publish-matrix

container-sign-external:
  parallel:
    matrix: *build-matrix

test-ldap-smoke:
  stage: test
  extends: .dind
  image: "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:24.0.7"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: "never"
    - when: "on_success"
  before_script:
    # Allow that the Docker API version is negotiated between client and server
    - unset DOCKER_API_VERSION
    - export IMAGE_TAG=${RELEASE_VERSION}
    - echo -e "\e[0Ksection_start:`date +%s`:docker_debug[collapsed=true]\r\e[0KDocker version details"
    - echo $IMAGE_TAG
    - docker version
    - echo -e "\e[0Ksection_end:`date +%s`:docker_debug\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:docker_compose_config[collapsed=true]\r\e[0KDocker Compose configuration"
    - docker compose config test
    - echo -e "\e[0Ksection_end:`date +%s`:docker_compose_config\r\e[0K"
    - docker compose up --no-build --quiet-pull --wait --wait-timeout 60 nats ldap-server ldif-producer
  script:
    # - sleep 10
    - docker compose run --quiet-pull --rm test .venv/bin/pytest -v tests/unit tests/integration/
  after_script:
    - docker logs ldap-server >& ldap-server.log
    - docker logs ldif-producer >& ldif-producer.log
    - docker logs nats >& nats.log
    - docker compose down --volumes
  artifacts:
    paths:
      - ldap-server.log
      - ldif-producer.log
      - nats.log
    expire_in: "1 day"
    when: "always"
    expose_as: "docker compose server logs"

push-image-external:
  parallel:
    matrix: *publish-matrix

check-debian-updates:
  parallel:
    matrix: *publish-matrix
  variables:
    TARGET_IMAGE: "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest"

...
