---

stages:
- lint-stage
- build-stage
- test-stage
- publish-stage

variables:
  UNIV_ARTIFACTS: artifacts.knut.univention.de
  UNIV_DOCKERHUB_CACHE:
    ${UNIV_ARTIFACTS}/dockerhub_proxy_cache/
  UPX_IMAGE_REGISTRY:
    ${UNIV_ARTIFACTS}/upx/
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

  DOCKER_COMPOSE_PRODUCTION_FILES:
    --file docker-compose.yaml
    --file docker-compose.prod.yaml

  DOCKER_COMPOSE_BUILD_FILES:
    --file docker-compose.yaml
    --file docker-compose.override.yaml
    --file docker-compose.prod.yaml

default:
  before_script:
  - docker info
  - docker version
  - mkdir "$HOME/.docker/"
  # DOCKER_AUTH_CONFIG contains credenials for
  # https://artifacts.knut.univention.de/ and
  # https://quay.io/ (univention+git_knut_for_quay_io)
  - echo "$DOCKER_AUTH_CONFIG" > "$HOME/.docker/config.json"

pre-commit-job:
  tags:
    - docker
  stage: lint-stage
  image:
    name: ${UPX_IMAGE_REGISTRY}container-pre-commit/pre-commit:latest
    entrypoint: ["/bin/bash", "-c"]
  variables:
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
    - .cache/pip
    - .cache/pre-commit
    - venv/
  before_script:
  - echo "Explicitly skip the default action docker login"
  script:
  # The image currently supplies version 21.1.2
  - /venv/bin/python -m pip install --upgrade pip==21.1.3
  # pip/ruamel.yaml.clib depends on
  #   gcc to compile test_ruamel_yaml.c
  #   Scrt1.o and crti.o from musl-dev
  #   Python.h from python3-dev
  - apk add --no-cache gcc musl-dev python3-dev
  # Compose lint would fail without the referenced env files
  - cp .env.ldap-server.example .env.ldap-server
  - pip install pipenv==2021.5.29
  - pipenv check
  - pre-commit run --all-files

build-job:
  tags:
    - docker
  # Only the debian flavor seems to be working with dind out of the box
  # the alpine as of 1.29.2 does not because of a mismatch issue
  # between "musl libc" vs glibc:
  # https://github.com/docker/compose/issues/3465
  # https://stackoverflow.com/a/42322893
  image: ${UNIV_DOCKERHUB_CACHE}docker/compose:debian-1.29.2
  stage: build-stage
  services:
    - name: ${UNIV_DOCKERHUB_CACHE}library/docker:20.10.6-dind
      alias: docker
      command:
        - "--insecure-registry=artifacts.knut.univention.de"
        - "--tls=false"
  script:
  - apt-get update
  - apt-get --assume-yes --verbose-versions --no-install-recommends install python3-sh
  - python3 ci-build-script.py

test-job:
  tags:
    - docker
  image: ${UNIV_DOCKERHUB_CACHE}docker/compose:debian-1.29.2
  stage: test-stage
  services:
    - name: ${UNIV_DOCKERHUB_CACHE}library/docker:20.10.6-dind
      alias: docker
      command:
        - "--insecure-registry=artifacts.knut.univention.de"
        - "--tls=false"
  script:
    - cp .env.ldap-server.example .env.ldap-server
    - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} pull
    - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} up --detach --no-build
    - cd integration-test
    - docker-compose pull
    - docker-compose up --no-build --exit-code-from test
    - docker-compose rm
    - ls -lah robot_results
    - cd -
    - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} down
    - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} rm
  artifacts:
    when: always
    expire_in: 4 weeks
    reports:
      junit: integration-test/robot_results/xunit.xml
    paths:
    - integration-test/robot_results

publish-job:
  image: ${UNIV_DOCKERHUB_CACHE}docker/compose:debian-1.29.2
  stage: publish-stage
  tags:
    - docker
  only:
    - main
  services:
    - name: ${UNIV_DOCKERHUB_CACHE}library/docker:20.10.6-dind
      alias: docker
      command:
        - "--insecure-registry=artifacts.knut.univention.de"
        - "--tls=false"
  script:
  - apt-get update
  - apt-get --assume-yes --verbose-versions --no-install-recommends install python3-sh
  - python3 ci-publish-script.py

...
