---

stages:
- lint-stage
- build-stage
- test-stage
#- deploy-stage
#- test-stage
#- undeploy-stage

variables:
  UNIV_ARTIFACTS: artifacts.knut.univention.de
  UNIV_DOCKERHUB_CACHE:
    ${UNIV_ARTIFACTS}/dockerhub_proxy_cache/
  UPX_IMAGE_REGISTRY:
    ${UNIV_ARTIFACTS}/upx/
  # We need to turn off TLS or reconfigure GitLab, see:
  # https://about.gitlab.com/releases/
  # 2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_TLS_CERTDIR: ""
  # DOCKER_TLS_CERTDIR: "/certs"
  # DOCKER_TLS_VERIFY: 1
  # DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

  CI_PIPELINE_TAG: "${CI_PIPELINE_ID}-"

  DOCKER_COMPOSE_PRODUCTION_FILES:
    --file docker-compose.yaml
    --file docker-compose.prod.yaml

  DOCKER_COMPOSE_BUILD_FILES:
    ${DOCKER_COMPOSE_PRODUCTION_FILES}
    --file docker-compose.override.yaml


pre-commit-job:
  tags:
    - upx-docker
  stage: lint-stage
  image: ${UPX_IMAGE_REGISTRY}container-pre-commit/pre-commit:latest
  variables:
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
    - .cache/pip
    - .cache/pre-commit
    - venv/
  script:
  # Compose lint would fail without the referenced env files
  - cp .env.listener.example .env.listener
  - cp .env.univention-openldap.example .env.univention-openldap
  - pre-commit run --all-files

build-job:
  tags:
    - upx-docker
  # Only the debian flavor seems to be working with dind out of the box
  # the alpine as of 1.28.0 does not because of a mismatch issue
  # between "musl libc" vs glibc:
  # https://github.com/docker/compose/issues/3465
  # https://stackoverflow.com/a/42322893
  image: ${UNIV_DOCKERHUB_CACHE}docker/compose:debian-1.28.0
  stage: build-stage
  script:
    - cp .env.listener.example .env.listener
    - cp .env.univention-openldap.example .env.univention-openldap
    - docker-compose ${DOCKER_COMPOSE_BUILD_FILES} build
    - docker-compose ${DOCKER_COMPOSE_BUILD_FILES} push

#deploy-job:
#  image: ${UNIV_DOCKERHUB_CACHE}docker/compose:debian-1.28.0
#  stage: deploy-stage
#  tags:
#    - docker
#  when: manual
#  script:
#    - cp .env.listener.example .env.listener
#    - cp .env.univention-openldap.example .env.univention-openldap
#    - docker-compose pull
#    - docker-compose up --detach --no-build

test-job:
  tags:
    - upx-docker
  image: ${UNIV_DOCKERHUB_CACHE}docker/compose:debian-1.28.0
  stage: test-stage
  script:
    - cp .env.listener.example .env.listener
    - cp .env.univention-openldap.example .env.univention-openldap
    - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} pull
    - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} up --detach --no-build
    - cd integration-test
    - docker-compose pull
    - docker-compose up --no-build --exit-code-from test
    - docker-compose rm
    - ls -lah robot_results
    - cd -
    - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} down
    - docker-compose ${DOCKER_COMPOSE_PRODUCTION_FILES} rm
  artifacts:
    when: always
    expire_in: 4 weeks
    reports:
      junit: integration-test/robot_results/xunit.xml
    paths:
    - integration-test/robot_results


#undeploy-job:
#  image: ${UNIV_DOCKERHUB_CACHE}/docker/compose:debian-1.28.0
#  stage: undeploy-stage
#  tags:
#    - docker
#  when: manual
#  script:
#    - docker-compose down
#    - docker-compose rm
...
