---

# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH <info@univention.de>

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: "docker/ldap/patches/"

repos:
  # "Copy .env.ldap-server.example so that docker-compose.yaml can be linted"
  - repo: "local"
    hooks:
      - id: "copy-env-ldap-server"
        name: "copy-env-ldap-server"
        entry: "sh -c 'if [ ! -f .env.ldap-server ]; then cp .env.ldap-server.example .env.ldap-server; fi'"
        language: "system"
        files: "docker-compose.yaml"
        pass_filenames: false

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: "check-added-large-files"
        name: "check for added large files"
      - id: "check-executables-have-shebangs"
        name: "check that executables have shebangs"
      - id: "check-merge-conflict"
        name: "check for merge conflicts"
      - id: "check-yaml"
        name: "check yaml"
        args:
          - "--allow-multiple-documents"
          # Allow custom tags like Gitlab's "!reference" tag.
          - "--unsafe"
        exclude: "^helm/.+/templates/"
      - id: "end-of-file-fixer"
        name: "fix end of files"
        exclude: "^helm/.+/README.md$"
      - id: "fix-byte-order-marker"
        name: "fix utf-8 byte order marker"
      - id: "trailing-whitespace"
        name: "trim trailing whitespace"

  - repo: "https://github.com/compilerla/conventional-pre-commit"
    rev: "v3.0.0"
    hooks:
      - id: "conventional-pre-commit"
        name: "Conventional Commit"
        stages: ["commit-msg"]

  - repo: "https://git.knut.univention.de/univention/dist/pre-commit-hooks/addlicense"
    rev: "v1.0.0"
    hooks:
      - id: "addlicense"
        name: "Check or add license headers to files"
        args: []

  - repo: "https://github.com/google/yapf"
    rev: "v0.40.2"
    hooks:
      - id: "yapf"
        name: "yapf"

  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.1.8"
    hooks:
      - id: "ruff"
        name: "ruff"
        args:
          - "check"
          - "--fix"
          - "--show-source"
          - "--exit-non-zero-on-fix"
          - "--extend-select"
          - "COM"

  - repo: "https://github.com/pre-commit/mirrors-autopep8"
    rev: "v2.0.4"
    hooks:
      - id: "autopep8"
        name: "autopep8"
        args:
          - "--recursive"
          - "--in-place"

  - repo: "https://github.com/PyCQA/flake8"
    rev: "6.1.0"
    hooks:
      - id: "flake8"
        name: "flake8"

  - repo: "https://github.com/pylint-dev/pylint"
    rev: "v3.0.3"
    hooks:
      - id: "pylint"
        name: "pylint"
        additional_dependencies:
          - "pytest"
          - "ldap3"

  - repo: "https://github.com/hadolint/hadolint"
    rev: "v2.12.0"
    hooks:
      - id: "hadolint"
        name: "Lint Dockerfiles"
        args:
          - "--no-color"
          - "--strict-labels"

  - repo: "https://gitlab.com/univention/pre-commit-hooks/docker-compose-check"
    rev: "7702a8801a158b8595569dd29e2dd655d8a08310"
    hooks:
      - id: "docker-compose-check"
        name: "Validate docker-compose files (python)"

  # Cloned from github.com/IamTheFij/docker-pre-commit
  - repo: "https://gitlab.com/univention/pre-commit-hooks/docker-pre-commit"
    rev: "v3.0.1"
    hooks:
      - id: "docker-compose-check"
        name: "Validate docker compose files (bash)"

  - repo: "https://gitlab.com/univention/pre-commit-hooks/pre-commit-shell"
    rev: "v1.0.6+uv1"
    hooks:
      - id: "shell-lint"
        name: "Shell Syntax Check"
        args:
          - "--enable=all"

  - repo: "https://github.com/gruntwork-io/pre-commit"
    rev: "v0.1.23"
    hooks:
      - id: "shellcheck"
        name: "Shellcheck Bash Linter"
        args:
          - "--enable=all"
      - id: "helmlint"
        name: "helmlint"

  - repo: "https://github.com/norwoodj/helm-docs"
    rev: "v1.12.0"
    hooks:
      - id: "helm-docs"
        name: "Helm Docs"
        args:
          - "--chart-search-root=helm"
          - "--template-files=README.md.gotmpl"

  # Uses `GITLAB_SERVER`, `GITLAB_PROJECT_ID` and `GITLAB_PRIVATE_TOKEN`
  - repo: "https://gitlab.com/univention/pre-commit-hooks/gitlab-ci-linter"
    rev: "v1.0.6+uv2"
    hooks:
      - id: "gitlab-ci-linter"
        name: ".gitlab-ci.yml linter"

...
