---

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'images/ldap/patches/'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  - id: yapf

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8

- repo: https://github.com/PyCQA/pylint
  rev: pylint-2.6.0
  hooks:
  - id: pylint

# This is a wrapper for shellcheck as long as
# shellcheck doesn't have it's own .pre-commit-hooks.yaml
# https://github.com/koalaman/shellcheck/pull/1032
- repo: git://github.com/detailyang/pre-commit-shell
  rev: v1.0.6
  hooks:
  - id: shell-lint

- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint

- repo: https://gitlab.com/devopshq/gitlab-ci-linter
  rev: v1.0.1
  hooks:
  - id: gitlab-ci-linter
    args:
      - '--server'
      - 'https://git.knut.univention.de'
...
