---

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'docker/ldap/patches/'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  # "Check for added large files"
  - id: check-added-large-files
  # "Check for merge conflicts"
  - id: check-merge-conflict
  # "Check Yaml"
  - id: check-yaml
    exclude: ^helm/.+/templates/
  # "Fix End of Files"
  - id: end-of-file-fixer
    exclude: ^helm/.+/README.md
  # "Trim Trailing Whitespace"
  - id: trailing-whitespace

# "Commit messages"
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.1.1
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]

# "yapf"
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  - id: yapf
    exclude: ^docs/conf.py

# "flake8"
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    exclude: ^docs/conf.py

# "pylint"
- repo: https://github.com/PyCQA/pylint
  rev: v2.17.4
  hooks:
  - id: pylint
    additional_dependencies:
      - pytest
      - ldap3
    exclude: ^docs/conf\.py$

# "Shell Syntax Check"
# This is a wrapper for shellcheck as long as
# shellcheck doesn't have it's own .pre-commit-hooks.yaml
# https://github.com/koalaman/shellcheck/pull/1032
- repo: https://gitlab.com/univention/pre-commit-hooks/pre-commit-shell
  rev: v1.0.6
  hooks:
  - id: shell-lint

# "Dockerfile linter"
- repo: https://gitlab.com/univention/pre-commit-hooks/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint

# "docker-compose.yaml linter"
- repo: https://gitlab.com/univention/pre-commit/docker-compose-check
  rev: 7702a8801a158b8595569dd29e2dd655d8a08310
  hooks:
  - id: docker-compose-check

# "Runs hadolint installed on the local system"
- repo: https://gitlab.com/univention/pre-commit-hooks/docker-pre-commit
  rev: v2.0.0
  hooks:
  - id: hadolint-system

# ".gitlab-ci.yml linter"
# Disable temporarily because gitlab-api can not be accessed.
# "urllib.error.HTTPError: HTTP Error 401: Unauthorized"
#- repo: https://gitlab.com/univention/pre-commit-hooks/gitlab-ci-linter
#  rev: v1.0.1
#  hooks:
#  - id: gitlab-ci-linter
#    args:
#    - '--server'
#    - 'https://git.knut.univention.de'

# "Helm chart linter"
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.20
  hooks:
  - id: helmlint

- repo: https://github.com/norwoodj/helm-docs
  rev: v1.11.0
  hooks:
    - id: helm-docs
      args:
        - --chart-search-root=helm
        - --template-files=README.md.gotmpl

...
