---

services:
  ldap-notifier:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-notifier:latest
    build:
      context: ./images/notifier
    depends_on:
      ldap-server:
        condition: service_healthy
    ports:
    - 6669:6669
    volumes:
    - ldap-shared-data:/var/lib/univention-ldap/:rw
    - ldap-shared-run:/var/run/slapd/:ro

  ldap-server:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-server:latest
    build:
      context: ./images/ldap
    env_file: .env.ldap-server
    ports:
    - 389:389
    - 636:636
    secrets:
    - ca_cert
    - cert_pem
    - private_key
    volumes:
    - ./ssl/dh_2048.pem:/etc/ldap/dh_2048.pem:ro
    - ./saml/idp/:/usr/share/saml/idp/:ro
    - ldap-shared-data:/var/lib/univention-ldap/:rw
    - ldap-shared-run:/var/run/slapd/:rw

  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap-server':{'login':{'bind_id':'cn=admin,dc=univention-organization,dc=intranet'}}}]"
      PHPLDAPADMIN_HTTPS: "false"
    links:
      - ldap-server
    ports:
      - 8001:80

  docs:
    image: docker-registry.knut.univention.de/sphinx:latest
    working_dir: /docs/docs
    volumes:
      - ".:/docs"
    profiles:
      - docs

secrets:
  ca_cert:
    file: ssl/certs/CAcert.pem
  cert_pem:
    file: ssl/certs/cert.pem
  private_key:
    file: ssl/secret/private.key

volumes:
  ldap-shared-data:
  ldap-shared-run:

...
