---

name: "dev-local"

services:
  ldap-notifier:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-notifier:latest
    build:
      context: ./docker/notifier
    depends_on:
      ldap-server:
        condition: service_started
    ports:
    - 6669:6669
    volumes:
    - ldap-shared-data:/var/lib/univention-ldap/:rw
    - ldap-shared-run:/var/run/slapd/:ro

  ldap-server:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-server:latest
    build:
      context: ./docker/ldap
    env_file: .env.ldap-server
    ports:
    - 389:389
    - 636:636
    ## Enable the secrets below if TLS is desired and `uldap/start-tls` is set.
    # secrets:
    # - ca_cert
    # - cert_pem
    # - private_key
    # - dh_param
    volumes:
    - ./tests/base-defaults.conf:/etc/univention/base-defaults.conf:ro
    - ldap-shared-data:/var/lib/univention-ldap/:rw
    - ldap-shared-run:/var/run/slapd/:rw

  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap-server':{'login':{'bind_id':'cn=admin,dc=univention-organization,dc=intranet'}}}]"
      PHPLDAPADMIN_HTTPS: "false"
    links:
      - ldap-server
    ports:
      - 8001:80

  docs:
    image: docker-registry.knut.univention.de/sphinx:latest
    working_dir: /docs/docs
    volumes:
      - ".:/docs"
    profiles:
      - docs

  test:
    build:
      context: ./docker/testrunner/
    environment:
      PYTEST_ADDOPTS: --ldap-server=ldap-server
    profiles:
      - test
    volumes:
      - ".:/app"

  # Environment of the pre-commit linter.
  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

secrets:
  ca_cert:
    file: ssl/CAcert.pem
  cert_pem:
    file: ssl/cert.pem
  private_key:
    file: ssl/cert.key
  dh_param:
    file: ssl/dh_2048.pem

volumes:
  ldap-shared-data:
  ldap-shared-run:
  pre-commit-cache:

...
