---

services:
  ldap-notifier:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/notifier-server:latest
    build:
      context: ./images/notifier
    depends_on:
      ldap-server:
        condition: service_healthy
    ports:
    - 6669:6669
    volumes:
    - ldap-shared-listener-data:/var/lib/univention-ldap/listener/:rw
    - ldap-shared-notify-data:/var/lib/univention-ldap/notify/:rw
    - ldap-shared-run:/var/run/slapd/:ro

  ldap-server:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-server:latest
    build:
      context: ./images/ldap
    env_file: .env.ldap-server
    healthcheck:
      test: bash -c 'echo > /dev/tcp/localhost/389'
      interval: 2s
      timeout: 1s
      retries: 10
      start_period: 5s
    ports:
    - 389:389
    - 636:636
    secrets:
    - ca_cert
    - cert_pem
    - private_key
    volumes:
    - ./ssl/dh_2048.pem:/etc/ldap/dh_2048.pem:ro
    - ./saml/idp/:/usr/share/saml/idp/:ro
    - ldap-server-db-data:/var/lib/univention-ldap/ldap/:rw
    - ldap-server-last-id-data:/var/lib/univention-ldap/last-id-data/:rw
    - ldap-server-translog-data:/var/lib/univention-ldap/translog/:rw
    - ldap-shared-listener-data:/var/lib/univention-ldap/listener/:rw
    - ldap-shared-notify-data:/var/lib/univention-ldap/notify/:ro
    - ldap-shared-run:/var/run/slapd/:rw

secrets:
  ca_cert:
    file: ssl/certs/CAcert.pem
  cert_pem:
    file: ssl/certs/cert.pem
  private_key:
    file: ssl/secret/private.key

volumes:
  # OpenLDAP only
  ldap-server-db-data:
  ldap-server-last-id-data:
  ldap-server-translog-data:

  # Notifier + OpenLDAP
  ldap-shared-listener-data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  ldap-shared-notify-data:
  ldap-shared-run:

...
