---

version: '3.8'

services:
  listener:
    build:
      context: ./images/listener
      args:
        DEBIAN_BASE_IMAGE_TAG: buster-slim
    #image: bash:latest
    image: docker-registry.knut.univention.de/upx/container-ldap/listener:${CI_PIPELINE_TAG}test
    env_file: .env.listener
    #entrypoint: ["bash", "-c", "sleep 10; tail -f /var/lib/univention-ldap/listener/listener"]
    secrets:
    - ca_cert
    - cert_pem
  notifier:
    build:
      context: ./images/notifier
      args:
        DEBIAN_BASE_IMAGE_TAG: buster-slim
    image: docker-registry.knut.univention.de/upx/container-ldap/notifier:${CI_PIPELINE_TAG}test
    depends_on:
    - openldap
    ports:
    - 6669:6669
    volumes:
    - notify-transaction-data:/var/lib/univention-ldap/notify/:rw
    - ldap-run:/var/run/slapd/:ro
    - listener-data:/var/lib/univention-ldap/listener/:ro
  openldap:
    build:
      context: ./images/ldap
      args:
        DEBIAN_BASE_IMAGE_TAG: buster-slim
        DEB_BUILDER_REGISTRY: docker-registry.knut.univention.de
        DEB_BUILDER_IMAGE: univention-openldap_deb_builder
        DEB_BUILDER_TAG: latest
    image: docker-registry.knut.univention.de/upx/container-ldap/openldap:${CI_PIPELINE_TAG}test
    env_file: .env.univention-openldap
    ports:
    - 389:389
    - 636:636
    secrets:
    - ca_cert
    - cert_pem
    - private_key
    volumes:
    - ./ssl/dh_2048.pem:/etc/ldap/dh_2048.pem:ro
    - notify-transaction-data:/var/lib/univention-ldap/notify/:ro
    - db-data:/var/lib/univention-ldap/ldap/:rw
    - last-id-data:/var/lib/univention-ldap/last-id-data/:rw
    - ldap-run:/var/run/slapd/:rw
    - translog-data:/var/lib/univention-ldap/translog/:rw
    - listener-data:/var/lib/univention-ldap/listener/:rw

secrets:
  ca_cert:
    file: ssl/certs/CAcert.pem
  cert_pem:
    file: ssl/certs/cert.pem
  private_key:
    file: ssl/secret/private.key

volumes:
  # OpenLDAP only:
  db-data:
  last-id-data:
  ldap-run:
  translog-data:
  # Notifier + OpenLDAP
  notify-transaction-data:
  # Listener + OpenLDAP
  listener-data:
    driver_opts:
      type: tmpfs
      device: tmpfs

...
