---

version: '3.8'

services:
  listener:
    build:
      context: ./images/listener
      args:
        DEBIAN_BASE_IMAGE_TAG: buster-slim
    #image: bash:latest
    env_file: .env.listener
    #entrypoint: ["bash", "-c", "sleep 10; tail -f /var/lib/univention-ldap/listener/listener"]
    secrets:
    - ca_cert
    - cert_pem
    volumes:
    - listener-data:/var/lib/univention-ldap/listener/:ro
  openldap:
    build:
      context: ./images/ldap
      args:
        DEBIAN_BASE_IMAGE_TAG: buster-slim
    #image: docker-registry.knut.univention.de/univention-openldap:latest
    env_file: .env.univention-openldap
    ports:
    - 389:389
    - 636:636
    secrets:
    - ca_cert
    - cert_pem
    - private_key
    volumes:
    - ./ssl/dh_2048.pem:/etc/ldap/dh_2048.pem:ro
    - notify-transaction-data:/var/lib/univention-ldap/notify/:ro
    - db-data:/var/lib/univention-ldap/ldap/:rw
    - last-id-data:/var/lib/univention-ldap/last-id-data/:rw
    - translog-data:/var/lib/univention-ldap/translog/:rw
    - listener-data:/var/lib/univention-ldap/listener/:rw

secrets:
  ca_cert:
    file: ssl/certs/CAcert.pem
  cert_pem:
    file: ssl/certs/cert.pem
  private_key:
    file: ssl/secret/private.key

volumes:
  # OpenLDAP only:
  db-data:
  last-id-data:
  translog-data:
  # Notifier + OpenLDAP
  notify-transaction-data:
  # Listener + OpenLDAP
  listener-data:
    driver_opts:
      type: tmpfs
      device: tmpfs

...
