---

version: '3.8'

services:
  test:
    build:
      context: ./
      args:
        BASE_IMAGE_REGISTRY: docker-registry.knut.univention.de/
    image: docker-registry.knut.univention.de/acceptance_test:latest
    entrypoint: sh -c "cd /tests && robot --xunit xunit.xml --outputdir /test_output/robot_results tests"
    networks:
    - public_ldap
    volumes:
    - ./:/test_output:rw

networks:
  public_ldap:
    external:
      name: container-ldap_default

...
