---

version: '3.8'

services:
  test:
    build:
      context: ./
      args:
        BASE_IMAGE_REGISTRY: docker-registry.knut.univention.de/
    image: docker-registry.knut.univention.de/acceptance_test:latest
    entrypoint: robot --xunit xunit.xml --outputdir /tests/robot_results --consolecolors=on tests
    environment:
    - TERM=xterm
    networks:
    - public_ldap
    volumes:
    - ./:/tests:rw
    working_dir: /tests

networks:
  public_ldap:
    external:
      name: container-ldap_default

...
