# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---

version: '3.8'

services:
  test:
    image:
     artifacts.knut.univention.de/upx/container-test-automation/integration-test
    entrypoint: robot
                  --xunit xunit.xml
                  --outputdir /tests/robot_results
                  --consolecolors=on
                  tests
    environment:
    - TERM=xterm
    networks:
    - public_ldap
    volumes:
    - ./:/tests:rw
    working_dir: /tests

networks:
  public_ldap:
    external:
      name: container-ldap_default

...
