---
{{ include "common.configMap" (dict "top" . "overrides" "ldap-server.configMap") }}

{{- define "ldap-server.configMap" }}
{{- with .top }}
data:
  ENVIRONMENT: "{{ .Values.ldapServer.environment }}"
  LDAP_CN_ADMIN_PW: '{{ required "ldapSecret is required" .Values.ldapServer.ldapSecret }}'
  CA_CERT_FILE: "{{ .Values.ldapServer.caCertFile }}"
  CERT_PEM_FILE: "{{ .Values.ldapServer.certPemFile }}"
  PRIVATE_KEY_FILE: "{{ .Values.ldapServer.privateKeyFile }}"
  DH_PARAM_FILE: "{{ .Values.ldapServer.dhParamFile }}"
{{- end }}
{{- end }}
