{{/*
SPDX-FileCopyrightText: 2024-2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: "{{ include "common.names.fullname" . }}"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  DOMAIN_NAME: {{ ( coalesce .Values.ldapServer.config.domainName .Values.global.ldap.domainName ) | required "Either .Values.ldapServer.config.domainName or .Values.global.ldap.domainName must be set." | quote }}
  LDAP_BASE_DN: {{ ( coalesce .Values.ldapServer.config.ldapBaseDn .Values.global.ldap.baseDn ) | required "Either .Values.ldapServer.config.ldapBaseDn or .Values.global.ldap.baseDn must be set." | quote }}
  LOG_LEVEL: {{ .Values.ldapServer.config.logLevel | required ".Values.ldapServer.config.logLevel is required" | quote }}
  PYTHON_LOG_LEVEL: {{ .Values.ldapServer.config.pythonLogLevel | required ".Values.ldapServer.config.pythonLogLevel is required" | quote }}
  SAML_METADATA_URL: {{ include "ldap-server.samlMetadataUrl" . | quote }}
  SAML_METADATA_URL_INTERNAL: {{ include "ldap-server.samlMetadataUrlInternal" . | quote }}
  SERVICE_PROVIDERS: {{ include "ldap-server.samlServiceProviders" . | quote }}
  {{- if .Values.ldapServer.tls.enabled }}
  TLS_MODE: "secure"
  CA_CERT_FILE: "{{ .Values.ldapServer.tls.caCertificateFile }}"
  CERT_PEM_FILE: "{{ .Values.ldapServer.tls.certificateFile }}"
  PRIVATE_KEY_FILE: "{{ .Values.ldapServer.tls.certificateKeyFile }}"
  DH_PARAM_FILE: "/dhparam/dhparam.pem"
  {{- if .Values.ldapServer.tls.TLSCipherSuite }}
  LDAP_TLS_CIPHERSUITE: {{ .Values.ldapServer.tls.TLSCipherSuite | quote }}
  {{- end }}
  {{- else }}
  TLS_MODE: "off"
  {{- end }}
  UPDATE_INDEX_ON_STARTUP: {{ .Values.ldapServer.config.updateIndexOnStartup | required ".Values.ldapServer.config.updateIndexOnStartup is required" | quote }}
...
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-scripts" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  wait-for-saml-metadata.sh: |
    #!/bin/bash

    set -euo pipefail

    # we have no UCR in this container, so just grep the SAML URL from the config file
    UCR_FILES="/etc/univention/base-defaults.conf /etc/univention/base.conf /etc/univention/base-forced.conf"
    SAML_METADATA_URL=$(grep --no-filename '^umc/saml/idp-server:' $UCR_FILES 2>/dev/null | cut --delimiter=':' --fields='2-' | tail --lines=1 | xargs || true)
    SAML_METADATA_URL_INTERNAL=$(grep --no-filename '^umc/saml/idp-server-internal:' $UCR_FILES 2>/dev/null | cut --delimiter=':' --fields='2-' | tail --lines=1 | xargs || true)

    DOWNLOAD_URL=${SAML_METADATA_URL_INTERNAL:-${SAML_METADATA_URL}}
    echo "Checking endpoint ${DOWNLOAD_URL}."

    SECONDS=0
    TIMEOUT=120

    while ! curl -k -o /dev/null -sf "${DOWNLOAD_URL}"; do
      echo "Checking if the SAML Metadata can be downloaded from keycloak ..."
      sleep 2

      if (($SECONDS > $TIMEOUT)); then
        echo "Giving up after $TIMEOUT seconds"
        exit 1
      fi
    done

    echo "Success, the SAML Metadata is available."
  init-internal-database.sh: |
    #!/bin/bash

    set -uo pipefail
    mkdir -p /var/lib/univention-ldap/internal
    echo "dn: cn=internal
    objectClass: organizationalRole
    " | slapadd -b cn=internal -f /etc/ldap/slapd.conf

    echo "dn: cn=blocklists,cn=internal
    cn: blocklists
    objectClass: organizationalRole
    objectClass: univentionObject
    univentionObjectType: container/cn
    " | slapadd -b cn=internal -f /etc/ldap/slapd.conf
    exit 0

...
