---
{{ include "common.configMap" (dict "top" . "overrides" "ldap-server.configMap") }}

{{- define "ldap-server.configMap" }}
{{- with .top }}
data:
  DOMAIN_NAME: "{{ .Values.ldap_server.domain_name }}"
  ENVIRONMENT: "{{ .Values.ldap_server.environment }}"
  LDAP_BASE_DN: "{{ .Values.ldap_server.ldap_base_dn }}"
  CA_CERT_FILE: "{{ .Values.ldap_server.ca_cert_file }}"
  CERT_PEM_FILE: "{{ .Values.ldap_server.cert_pem_file }}"
  PRIVATE_KEY_FILE: "{{ .Values.ldap_server.private_key_file }}"
  SERVICE_PROVIDERS: "{{ .Values.ldap_server.service_providers }}"
  LDAP_CN_ADMIN_PW_HASH: '{{ required "ldap_admin_pw_hash is required" .Values.ldap_server.ldap_admin_pw_hash }}'
  {{- if .Values.ldap_server.ldap_tls_ciphersuite }}
  LDAP_TLS_CIPHERSUITE: "{{ .Values.ldap_server.ldap_tls_ciphersuite }}"
  {{- end }}
{{- end }}
{{- end }}
