{{/*
SPDX-FileCopyrightText: 2024 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: "{{ include "common.names.fullname" . }}"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  DOMAIN_NAME: {{ ( coalesce .Values.ldapServer.config.domainName .Values.global.ldap.domainName ) | required "Either .Values.ldapServer.config.domainName or .Values.global.ldap.domainName must be set." | quote }}
  LDAP_BASE_DN: {{ ( coalesce .Values.ldapServer.config.ldapBaseDn .Values.global.ldap.baseDn ) | required "Either .Values.ldapServer.config.ldapBaseDn or .Values.global.ldap.baseDn must be set." | quote }}
  LOG_LEVEL: {{ .Values.ldapServer.config.logLevel | required ".Values.ldapServer.config.logLevel is required" | quote }}
  SAML_METADATA_URL: {{ include "ldap-server.samlMetadataUrl" . | quote }}
  SAML_METADATA_URL_INTERNAL: {{ include "ldap-server.samlMetadataUrlInternal" . | quote }}
  SERVICE_PROVIDERS: {{ include "ldap-server.samlServiceProviders" . | quote }}
  {{- if .Values.ldapServer.tls.enabled }}
  TLS_MODE: "secure"
  CA_CERT_FILE: "{{ .Values.ldapServer.tls.caCertificateFile }}"
  CERT_PEM_FILE: "{{ .Values.ldapServer.tls.certificateFile }}"
  PRIVATE_KEY_FILE: "{{ .Values.ldapServer.tls.certificateKeyFile }}"
  DH_PARAM_FILE: "/dhparam/dhparam.pem"
  {{- if .Values.ldapServer.tls.TLSCipherSuite }}
  LDAP_TLS_CIPHERSUITE: {{ .Values.ldapServer.tls.TLSCipherSuite | quote }}
  {{- end }}
  {{- else }}
  TLS_MODE: "off"
  {{- end }}
...
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-scripts" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  wait-for-saml-metadata.sh: |
    #!/bin/bash

    set -euxo pipefail

    # we have no UCR in this container, so just grep the SAML URL from the config file
    UCR_FILES="/etc/univention/base-defaults.conf /etc/univention/base.conf /etc/univention/base-forced.conf"
    SAML_METADATA_URL=$(grep --no-filename '^umc/saml/idp-server:' $UCR_FILES 2>/dev/null | cut --delimiter=':' --fields='2-' | tail --lines=1 | xargs || true)
    SAML_METADATA_URL_INTERNAL=$(grep --no-filename '^umc/saml/idp-server-internal:' $UCR_FILES 2>/dev/null | cut --delimiter=':' --fields='2-' | tail --lines=1 | xargs || true)

    DOWNLOAD_URL=${SAML_METADATA_URL_INTERNAL:-${SAML_METADATA_URL}}
    echo "Checking endpoint ${DOWNLOAD_URL}."

    SECONDS=0
    TIMEOUT=120

    while ! curl -k -o /dev/null -sf "${DOWNLOAD_URL}"; do
      echo "Checking if the SAML Metadata can be downloaded from keycloak ..."
      sleep 2

      if (($SECONDS > $TIMEOUT)); then
        echo "Giving up after $TIMEOUT seconds"
        exit 1
      fi
    done

    echo "Success, the SAML Metadata is available."
  init-internal-database.sh: |
    #!/bin/bash

    set -uxo pipefail
    echo "dn: cn=internal
    objectClass: organizationalRole
    " | slapadd -b cn=internal -f /etc/ldap/slapd.conf
    exit 0

  is_active_master.sh: |
    #!/bin/bash
    set -uxo pipefail

    # Set variables
    POD_NAME="${HOSTNAME}"
    HEADLESS_SERVICE_NAME="${PRIMARY_SERVICE}"
    LDAP_URI="${LDAP_PROTOCOL}://127.0.0.1:${LDAP_PORT}"
    LDAP_BIND_DN="${ADMIN_DN}"
    LDAP_BIND_PASSWORD="${LDAP_CN_ADMIN_PW}"
    LOCK_DN="cn=replicationlock,${LDAP_BASEDN}"

    # Function to check if the current pod is the active master
    is_active_master() {
      # Check if the lock entry exists
      ldapsearch -H "$LDAP_URI" -x -D "$LDAP_BIND_DN" -w "$LDAP_BIND_PASSWORD" -b "$LOCK_DN" -s base "(objectClass=*)" >/dev/null 2>&1
      if [ $? -ne 0 ]; then
        # Lock entry doesn't exist, try to create it
        echo "dn: $LOCK_DN
    changetype: add
    objectClass: top
    objectClass: extensibleObject
    objectClass: organizationalRole
    description: $POD_NAME" | ldapmodify -H "$LDAP_URI" -x -D "$LDAP_BIND_DN" -w "$LDAP_BIND_PASSWORD"
        if [ $? -eq 0 ]; then
          echo "Acquired lock, becoming the active master"
          return 0
        else
          echo "Failed to acquire lock, another master is active"
          return 1
        fi
      else
        # Lock entry exists, check if it matches the current pod name
        active_master=$(ldapsearch -H "$LDAP_URI" -x -D "$LDAP_BIND_DN" -w "$LDAP_BIND_PASSWORD" -b "$LOCK_DN" -s base "(objectClass=*)" description | grep ^description: | awk '{print $2}')
        if [ "$active_master" == "$POD_NAME" ]; then
          echo "Current pod is the active master"
          return 0
        else
          echo "Another pod is the active master: $active_master"

          # Check if the other master is alive
          other_master_uri="${LDAP_PROTOCOL}://$active_master.${HEADLESS_SERVICE_NAME}:${LDAP_PORT}"
          ldapsearch -H "$other_master_uri" -x -D "$LDAP_BIND_DN" -w "$LDAP_BIND_PASSWORD" -b "$LOCK_DN" -s base "(objectClass=*)" >/dev/null 2>&1
          if [ $? -ne 0 ]; then
            echo "Other master is not responding, attempting to acquire lock"
            echo "dn: $LOCK_DN
    changetype: modify
    replace: description
    description: $POD_NAME" | ldapmodify -H "$LDAP_URI" -x -D "$LDAP_BIND_DN" -w "$LDAP_BIND_PASSWORD"
            if [ $? -eq 0 ]; then
              echo "Acquired lock, becoming the active master"
              return 0
            else
              echo "Failed to acquire lock, another master is active"
              return 1
            fi
          else
            echo "Other master is alive, remaining as a standby"
            return 1
          fi
        fi
      fi
    }

    # Call the is_active_master function
    is_active_master
...
