---
{{ include "common.configMap" (dict "top" . "overrides" "ldap-server.configMap") }}

{{- define "ldap-server.configMap" }}
{{- with .top }}
data:
  DOMAIN_NAME: "{{ .Values.ldap_server.domain_name }}"
  ENVIRONMENT: "{{ .Values.ldap_server.environment }}"
  LDAP_BASE_DN: "{{ .Values.ldap_server.ldap_base_dn }}"
  LDAP_CN_ADMIN_PW: '{{ required "ldap_admin_pw is required" .Values.ldap_server.ldap_admin_pw }}'
  LOG_LEVEL: "{{ .Values.ldap_server.log_level }}"
  CA_CERT_FILE: "{{ .Values.ldap_server.ca_cert_file }}"
  CERT_PEM_FILE: "{{ .Values.ldap_server.cert_pem_file }}"
  PRIVATE_KEY_FILE: "{{ .Values.ldap_server.private_key_file }}"
  DH_PARAM_FILE: "{{ .Values.ldap_server.dh_param_file }}"
  {{- if .Values.ldap_server.ldap_tls_ciphersuite }}
  LDAP_TLS_CIPHERSUITE: "{{ .Values.ldap_server.ldap_tls_ciphersuite }}"
  {{- end }}
  SAML_METADATA_URL: "{{ .Values.ldap_server.saml_metadata_url }}"
  SAML_METADATA_URL_INTERNAL: "{{ .Values.ldap_server.saml_metadata_url_internal }}"
  SERVICE_PROVIDERS: "{{ .Values.ldap_server.service_providers }}"
  TLS_MODE: '{{ required "tls_mode is required" .Values.ldap_server.tls_mode }}'
{{- end }}
{{- end }}
