
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

{{- if .Values.ldifProducer.enabled }}
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-ldif-producer-config" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
data:
  SOCKET_FILE_LOCATION: "/var/lib/univention-ldap/slapd-sock/sock"
  # TODO: Actually respect the Log Level in the code
  LOG_LEVEL: {{ required ".Values.ldifProducer.config.logLevel is required." .Values.ldifProducer.config.logLevel | quote  }}
  NATS_HOST: {{ tpl
    ( required
      "The Nats connection has to be configured, See ldifProducer.nats.connection.host."
      ( coalesce .Values.ldifProducer.nats.connection.host ((.Values.global.nats).connection).host )
    ) . | quote }}
  NATS_PORT: {{ tpl
    ( required
      "The Nats connection has to be configured, See ldifProducer.nats.connection.port."
      ( coalesce .Values.ldifProducer.nats.connection.port ((.Values.global.nats).connection).port )
    ) . | quote }}
  NATS_USERNAME: {{ tpl
    ( required
      "A Nats username has to be supplied, see parameter ldifProducer.nats.auth.username"
      .Values.ldifProducer.nats.auth.username
    ) . | quote }}
  NATS_MAX_RECONNECT_ATTEMPTS: {{ required ".Values.ldifProducer.nats.natsMaxReconnectAttempts is required." .Values.ldifProducer.nats.natsMaxReconnectAttempts | quote }}
  MAX_IN_FLIGHT_LDAP_MESSAGES: {{ required ".Values.ldifProducer.config.maxInFlightLdapMessages is required." .Values.ldifProducer.config.maxInFlightLdapMessages | quote }}
  BACKPRESSURE_WAIT_TIMEOUT: {{ required ".Values.ldifProducer.config.backpressureWaitTimeout is required." .Values.ldifProducer.config.backpressureWaitTimeout | quote }}
  LDAP_THREADS: {{ required ".Values.ldifProducer.config.ldapThreads is required." .Values.ldifProducer.config.ldapThreads | quote }}
  LDAP_BASE_DN: {{ include "nubusTemplates.ldapServer.ldap.baseDn" . | quote }}
  IGNORE_TEMPORARY_OBJECTS: "true"
...
{{- end }}
