{{/*
SPDX-FileCopyrightText: 2024 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-primary" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  PRIMARY_LDAP_URI: {{ include "nubusTemplates.ldapServer.ldap.connection.uriPrimary" . | quote }}
  LDAP_BASEDN: {{ include "nubusTemplates.ldapServer.ldap.baseDn" . | quote }}
  SYNC_USER_DN: {{ include "nubusTemplates.ldapServer.ldap.adminDn" . | quote}}
...
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-primary-config-templates" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  slapd.conf.tpl: |
    overlay syncprov
    syncprov-checkpoint 100 10
    syncprov-sessionlog 100

  append-slapd.conf.sh: |
    #!/usr/bin/env bash
    set -euxo pipefail

    # Export the SERVERID
    export SERVERID=$(echo ${HOSTNAME} | awk -F '-' '{print $(NF)+1}')

    # Read the slapd.conf.tpl file
    template=$(cat /config/templates/slapd.conf.tpl)

    # Replace placeholders with environment variable values using sed and eval
    while IFS=$'\n' read -r line; do
      # Skip empty lines
      if [[ -z "$line" ]]; then
        continue
      fi

      # Get the leading spaces from the line
      leading_spaces=$(echo "$line" | sed -n 's/^\(\s*\).*/\1/p')

      # Evaluate the line to expand any environment variables
      evaluated_line=$(eval echo "$line")

      # Prepend the leading spaces to the evaluated line
      evaluated_line="${leading_spaces}${evaluated_line}"

      # Escape special characters in the line
      escaped_line=$(echo "$line" | sed 's|[\/&]|\\&|g; s|\.|\\.|g; s|\+|\\+|g; s|\=|\\=|g')

      # Replace the line in the template with the evaluated line, preserving indentation
      template=$(echo "$template" | sed "s|^$escaped_line|$evaluated_line|")
    done < <(echo "$template")

    # Read the existing slapd.conf file
    slapd_conf=$(cat /etc/ldap/slapd.conf)

    # Initialize an empty modified slapd.conf file
    modified_slapd_conf="serverID 2$SERVERID\n"

    # Initialize the replication ID counter
    replication_id=1

    # Initialize the suffix variable
    suffix=""

    # Process the slapd.conf file line by line
    while IFS=$'\n' read -r line; do
      # Append the current line to the modified slapd.conf
      modified_slapd_conf+="$line\n"

      # Check if the current line starts with "suffix"
      if [[ "$line" =~ ^suffix ]]; then
        # Extract the suffix value
        suffix=$(echo "$line" | awk '{print $2}')
      fi

      # Check if the current line starts with "rootdn"
      if [[ "$line" =~ ^rootdn ]]; then
        # Generate the syncrepl configuration with the current replication ID and suffix
        syncrepl_config=$(echo "$template" | sed "s/PLACEHOLDER_REPLICATION_ID/$replication_id/" | sed "s|PLACEHOLDER_LDAP_BASEDN|$suffix|")

        # Append the syncrepl configuration to the modified slapd.conf, preserving indentation
        modified_slapd_conf+="$syncrepl_config\n"

        # Increment the replication ID
        replication_id=$((replication_id + 1))
      fi
    done < <(echo "$slapd_conf")

    # Write the modified slapd.conf
    echo -e "$modified_slapd_conf" > /etc/ldap/slapd.conf
    cat /etc/ldap/slapd.conf
...
