---
{{ include "common.secret" (dict "top" . "overrides" "ldap-server.secret") }}

{{- define "ldap-server.secret" }}
{{- with .top }}
data:
  ca_cert: "{{ .Values.ldap_server.ca_cert }}"
  cert_pem: "{{ .Values.ldap_server.cert_pem }}"
  private_key: "{{ .Values.ldap_server.private_key }}"
  dh_param: "{{ .Values.ldap_server.dh_param }}"
{{- end }}
{{- end }}
