---
{{ include "common.secret" (dict "top" . "overrides" "ldap-server.secret") }}

{{- define "ldap-server.secret" }}
{{- with .top }}
data:
  ca_cert: "{{ .Values.ldapServer.caCert }}"
  cert_pem: "{{ .Values.ldapServer.certPem }}"
  private_key: "{{ .Values.ldapServer.privateKey }}"
  dh_param: "{{ .Values.ldapServer.dhParam }}"
{{- end }}
{{- end }}
