{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- $_ := required "A ldapServer password has to be supplied, see parameter ldapServer.auth." (coalesce .Values.ldapServer.auth.password (.Values.ldapServer.auth.existingSecret).name) }}
{{- if not (.Values.ldapServer.auth.existingSecret).name }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "credentials" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
stringData:
  adminPassword: {{ .Values.ldapServer.auth.password | quote }}
{{- end }}
