{{/*
SPDX-FileCopyrightText: 2024-2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.serviceAccount.annotations .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs:
    - create
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs:
    - watch
    - get
    - update
  resourceNames: ["ldap-primary-leader"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["patch"]
  resourceNames:
    - {{ include "common.names.fullname" . }}-primary-0
    - {{ include "common.names.fullname" . }}-primary-1
- apiGroups: [""]
  resources: ["services"]
  verbs: ["patch"]
  resourceNames:
    - {{ include "common.names.fullname" . }}-primary
{{- /* Status ConfigMap

     Create cannot be restricted to a resource name.

     See:  https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources
*/}}
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "update", "patch"]
  resourceNames:
    - {{ printf "%s-status" (include "common.names.fullname" .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
subjects:
- kind: ServiceAccount
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ include "common.names.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
