{{/*
SPDX-FileCopyrightText: 2024-2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ printf "%s-secondary" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.service.annotations .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
spec:
  type: "ClusterIP"
  clusterIP: "None"
  publishNotReadyAddresses: true
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: "{{ $key }}"
      port: {{ $value.port }}
      targetPort: {{ $key | quote }}
      protocol: "{{ $value.protocol | default "TCP" }}"
    {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    ldap-server-type: secondary
...
