apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  serviceName: {{ include "common.names.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      # TODO: Remove `Values.imagePullSecrets` once it has been replaced by `image.pullSecrets` everywhere.
      {{- with (coalesce .Values.image.pullSecrets .Values.imagePullSecrets ) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.ldapServer.waitForSamlMetadata }}
        - name: wait-for-saml-metadata
          command: ["/bin/bash", "/scripts/wait-for-saml-metadata.sh"]
          {{ with .Values.image.waitForDependency }}
          image: "{{ if .registry }}{{ .registry }}/{{ end }}{{ .repository }}{{ if .sha256 }}@sha256:{{ .sha256 }}{{ else }}:{{ .tag }}{{ end }}"
          imagePullPolicy: "{{ .pullPolicy }}"
          {{ end }}
          envFrom:
            - configMapRef:
                name: {{ include "common.names.fullname" . }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: "config-map-ucr-defaults"
              mountPath: "/etc/univention/base-defaults.conf"
              subPath: "base.conf"
            {{- if (and .Values.global .Values.global.configMapUcr) }}
            - name: "config-map-ucr"
              mountPath: "/etc/univention/base.conf"
              subPath: "base.conf"
            {{- end }}
            {{- if (and .Values.global .Values.global.configMapUcrForced) }}
            - name: "config-map-ucr-forced"
              mountPath: "/etc/univention/base-forced.conf"
              subPath: "base.conf"
            {{- end }}
          resources:
            {{- toYaml .Values.resourcesWaitForDependency | nindent 12 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ if .Values.image.registry }}{{ .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}{{ if .Values.image.sha256 }}@sha256:{{ .Values.image.sha256 }}{{ else }}:{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "common.names.fullname" . }}
          volumeMounts:
            - name: "config-map-ucr-defaults"
              mountPath: "/etc/univention/base-defaults.conf"
              subPath: "base.conf"
            {{- if (and .Values.global .Values.global.configMapUcr) }}
            - name: "config-map-ucr"
              mountPath: "/etc/univention/base.conf"
              subPath: "base.conf"
            {{- end }}
            {{- if (and .Values.global .Values.global.configMapUcrForced) }}
            - name: "config-map-ucr-forced"
              mountPath: "/etc/univention/base-forced.conf"
              subPath: "base.conf"
            {{- end }}
            - name: secrets
              # TODO: conflict with /run/secrets, should use a namespace
              mountPath: /var/secrets
            - name: shared-data
              mountPath: /var/lib/univention-ldap
            - name: shared-run
              mountPath: /var/run/slapd
          ports:
            - name: ldap
              containerPort: 389
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: "config-map-ucr-defaults"
        configMap:
          name: {{ required "Please provide the name of the UCR ConfigMap in .Values.global.configMapUcrDefaults!" .Values.global.configMapUcrDefaults | quote }}
      {{- if (and .Values.global .Values.global.configMapUcr) }}
      - name: "config-map-ucr"
        configMap:
          name: "{{ .Values.global.configMapUcr }}"
      {{- end }}
      {{- if (and .Values.global .Values.global.configMapUcrForced) }}
      - name: "config-map-ucr-forced"
        configMap:
          name: "{{ .Values.global.configMapUcrForced }}"
      {{- end }}
      - name: secrets
        secret:
          secretName: {{ include "common.names.fullname" . | quote }}
      - name: scripts
        configMap:
          name: "{{ include "common.names.fullname" . }}-scripts"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: shared-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.persistence.sharedData.storageClass }}
      storageClassName: {{ .Values.persistence.sharedData.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.sharedData.size | required ".Values.persistence.sharedData.size is required" | quote }}
  - metadata:
      name: shared-run
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.persistence.sharedRun.storageClass }}
      storageClassName: {{ .Values.persistence.sharedRun.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.sharedRun.size | required ".Values.persistence.sharedRun.size is required" | quote }}
