# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---

## Global values
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - ldap-server
        topologyKey: kubernetes.io/hostname

environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []

# -- Application configuration for the Univention Directory Notifier
ldapNotifier:
  # -- TODO: Clarify usage of this parameter
  environment: "production"


## Docker image
image:
  pullPolicy: "IfNotPresent"
  pullSecrets: []
  registry: "gitregistry.knut.univention.de"
  repository: "univention/customers/dataport/upx/container-ldap/ldap-notifier"
  tag: "latest"
  ## Define image sha256 as an alternative to `tag`
  # sha256:


volumes:
  # -- Mapping of volumes to the volume claim names to use. Those have to match
  # the volumes of the "ldap-server".
  claims:
    shared-data: "shared-data-ldap-server-0"
    shared-run: "shared-run-ldap-server-0"


service:
  enabled: true
  type: ClusterIP
  ports:
    notifier:
      port: 6669
      protocol: "TCP"
  sessionAffinity:
    enabled: false
    timeoutSeconds: 10800


## Deployment resources
resources:
  # requests:
  #   memory: "512Mi"
  #   cpu: "250m"
  # limits:
  #   memory: "4Gi"
  #   cpu: "4"


autoscaling:
  enabled: false
...
